config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, skip: :registrations, controllers: { sessions: 'users/sessions' }
  root 'home#index'

  resources :blogs, path: 'blog'
  get 'games', to: 'games#index'
  get 'games/catcher'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user

  validates :title, presence: true

  # def get_date(pattern = "%d-%m-%Y")
  #   created_at.strftime(pattern)
  # end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

# Blog class
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tags
  before_action :correct_user, only: [:edit, :update, :destroy]



  def get_date(pattern = "%d-%m-%Y")
    created_at.strftime(pattern)
  end

  def correct_user
    if !current_user.admin?
      @blog = current_user.blogs.find_by(params[:id])
    else
      @blog = Blog.find(params[:id])
    end
    redirect_to blogs_path, notice: "No, no" if @blog.nil?
  end

  def set_tags
    @tags = ['Update', 'Opinion', nil]
  end

  # GET /blogs or /blogs.json
  def index
    @blog = Blog.order('created_at desc')
    return if params[:tag].blank?

    @blog = @blog.where(tag: params[:tag])

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # GET /blogs/1 or /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = current_user.blogs.new()
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)
    @blog.name = current_user.name
    @blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :content, :tag)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def get_date(blog, pattern = "%d-%m-%Y")
    blog.created_at.strftime(pattern)
  end

end

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :tag
    = f.select :tag, @tags
  .actions
    = f.submit 'Save'

app/views/blogs/_table.html.haml
#blogs
  - @blog.each do |b|
    .blog_box
      %p.post_author= b.name
      %h3.post_heading= link_to b.title, b
      %p.post_tag= b.tag
      - sentence_array= b.content.split(".")
      - first_sentence= sentence_array[0] + "." if sentence_array[0]
      - second_sentence= sentence_array[1].split.first + "..." if sentence_array[1]
      %p.post_body= "#{first_sentence} #{second_sentence}"
      %p.date= get_date(b)

app/views/blogs/edit.html.haml
%h1 Editing blog

= render 'form'

= link_to 'Show', @blog
\|
= link_to 'Back', blogs_path

app/views/blogs/index.html.haml
%h1 Listing blogs

.container
  .tools
    = form_with method: :get do |f|
      = f.select :tag, @tags, {}, {class: 'select_bar'}
      = button_tag 'Find'
      = link_to 'Clear', blogs_path, remote: true, class: 'button'
  .content
    = render 'table'

app/views/blogs/index.js.haml
- content = j render "blogs/table"
$('#blogs').html("#{content}")

app/views/blogs/new.html.haml
%h1 New blog

= render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.haml
%p#notice= notice

.box
  %h1= @blog.title
  %p= simple_format(@blog.content)
  .float
    %h6.author.left.child= @blog.name
    %h6.date.right.child= get_date(@blog)
  .link
    - if @blog.user == current_user || current_user.try(:admin?)
      = link_to 'Edit', edit_blog_path(@blog)
      \|
      = link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' }
      \|
      = link_to 'Back', blogs_path